# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20171119_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens do Estoque'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
