# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20171119_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados_complementares.UnidadeMedida'),
        ),
        migrations.DeleteModel(
            name='UnidadeMedida',
        ),
    ]
