# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=80)),
                ('endereco', models.CharField(blank=True, max_length=130, null=True)),
                ('mais_detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=80)),
                ('item', models.CharField(max_length=80)),
                ('valor_unitario', models.CharField(blank=True, max_length=130, null=True)),
            ],
        ),
    ]
