# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('nome_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome')),
                ('abreviacao', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
    ]
